project:
  type: website
  output-dir: _site
  
website:
  title: "Media Coverage Analysis (2015-2025)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: page-1.qmd
        text: Page 1
      - href: page-2.qmd
        text: Page 2
  page-footer:
    left: "© 2025, DSAN5400 Group Project"
    
format:
  html:
    theme: cosmo
    css: styles/custom.scss
    toc: true
    page-layout: full

